version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/" # Location of your .devcontainer folder
    schedule:
      interval: "daily" # Can be "daily", "weekly", or "monthly"
    commit-message:
      prefix: "feat(dev)"
      include: "scope"
