name: Publish Devcontainer

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'
      - '.github/**'

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
            platform: linux/amd64
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dev container image for ${{ matrix.arch }}
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/majikmate/classroom-codespace-image
          imageTag: latest-${{ matrix.arch }}
          push: always
          platform: ${{ matrix.platform }}

  create-manifest:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create and push multi-arch manifest
        run: |
          docker manifest create ghcr.io/majikmate/classroom-codespace-image:latest \
            --amend ghcr.io/majikmate/classroom-codespace-image:latest-amd64 \
            --amend ghcr.io/majikmate/classroom-codespace-image:latest-arm64
          docker manifest push ghcr.io/majikmate/classroom-codespace-image:latest
